### ISSUE TITLE
JS Error, bei Rechnungserstellung

### ISSUE THREAD

**Issue by cglill** [Odoo-Austria/odoo-addons#29]
In unregelmäßigen Abständen produziert das POS eine Fehlermeldung (siehe Anhang) "Cannot read property 'finalize' of null". Zudem wird in Folge das Druckvorschaufenster angezeigt, statt wieder zur Übersicht zurück zu springen. Die Session muss in Folge geschlossen und neu gestartet werden.
![mms_20170426_105552](https://cloud.githubusercontent.com/assets/24571515/25482329/90dfa26e-2b51-11e7-926f-09977e460a77.jpg)

**Comment by wpichler** [comment]
i think this happens in the ReceiptScreenWidget in the click_next function.

After order / rksv the ReceiptScreenWidget will get called - and if auto print is enabled it will call click_next - so that the window will get closed automatically - and print automatically. The click_next function only does destroy the order.

I have no idea why the order is not available here anymore (it does get called with the selected order method).

The complete ReceiptScreenWidget Implementation is broken as far as i can see, the current implementation does assume that the selectedOrder will not change in any way. This is not very well done. It would be better to store the current selectedOrder - with which the ReceiptScreen got called / rendered within the screen - and use this one for all operations - and not the selectedOrder. 
Or bind on the selectedOrder Property and react if it got changed somewhere.

A quick workaround for this current bug would be to overwrite the click_next function - and add an extra check in it - so it will only call finalize if it got an order.

@wtaferner your thoughts ?

**Comment by wtaferner** [comment]
Should be fixed after https://github.com/Odoo-Austria/odoo-addons/commit/9f27677b9720e228c9050d5ce8ed5c260ce63304.
